### ISSUE TITLE
Error while detecting LGT on the test data

### ISSUE THREAD

**Issue by lyy005** [peterthorpe5/public_scripts#10]
Hi Peter,
I'm using Lateral_gene_transfer_prediction_tool/Lateral_gene_transfer_predictor.py to detect LGTs. I'm testing my setup using the test dataset (/home/Thorpe_HGT/public_scripts/Lateral_gene_transfer_prediction_tool/tests/inputs/blast_tax.tab). I used the following command and got the following errors. I've installed Samtools, Biopython and Numpy. Did I miss anything? 

Thank you for any suggestions! 

YY

`$ python /home/Thorpe_HGT/public_scripts/Lateral_gene_transfer_prediction_tool/Lateral_gene_transfer_predictor.py -p /home/Thorpe_HGT/NCBI_downloads/ -i blast_tax.tab --tax_filter_out 6656 --tax_filter_up_to 33208 -o LTG_results.out --tax_coloumn 14`

```
INFO: sys.version_info(major=3, minor=7, micro=10, releaselevel='final', serial=0)
INFO: Command-line: /home/Thorpe_HGT/public_scripts/Lateral_gene_transfer_prediction_tool/Lateral_gene_transfer_predictor.py -p /home/Thorpe_HGT/ -i blast_tax.tab --tax_filter_out 6656 --tax_filter_up_to 33208 -o LTG_results.out --tax_coloumn 14
INFO: Starting testing: Thu Aug 19 16:57:37 2021
INFO: loading NCBI files from : /home/Thorpe_HGT/
INFO: parsing Blast file blast_tax.tab
Traceback (most recent call last):
  File "/home/Thorpe_HGT/public_scripts/Lateral_gene_transfer_prediction_tool/Lateral_gene_transfer_predictor.py", line 862, in <module>
    tax_coloumn)
  File "/home/Thorpe_HGT/public_scripts/Lateral_gene_transfer_prediction_tool/Lateral_gene_transfer_predictor.py", line 269, in parse_blast_tab_file
    staxids, scientific_name, scomnames, Kingdom = line.rstrip("\n").split("\t")
ValueError: not enough values to unpack (expected 17, got 1)
```

**Comment by peterthorpe5** [comment]
Hi YY,

It seems your BLAST file is not what is is expecting:

parse_blast_tab_file
staxids, scientific_name, scomnames, Kingdom = line.rstrip("\n").split("\t")
ValueError: not enough values to unpack (expected 17, got 1)


It was expecting 17 elements. Can you send me the first few line of this file?

Pete

**Comment by peterthorpe5** [comment]
FYI: This is a new tool as well: http://alienness.sophia.inra.fr/cgi/index.cgi

**Comment by lyy005** [comment]
Hi Pete,
Thanks for your reply. Thank you for suggesting the other tool. I'll give it a try too. 

I was using this file as the input: https://github.com/peterthorpe5/public_scripts/blob/master/Lateral_gene_transfer_prediction_tool/tests/inputs/blast_tax.tab

I've also made my own BLAST output and got the same error. Here's my command: 
`blastp -db /home/nr_database/nr -query AmiD.blast.out.fasta -outfmt "6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore salltitles staxids scientific_name scomnames sskingdoms" -evalue 1e-5 -num_threads 50 -out blast.out`

Here's the output: 
`jg24100.t1	ref|XP_015368240.1|	60.638	188	68	2	1	183	14	200	9.25e-77	238	PREDICTED: N-acetylmuramoyl-L-alanine amidase AmiD-like [Diuraphis noxia]	143948	Russian wheat aphid	Eukaryota
jg24100.t1	ref|XP_022180122.1|	61.376	189	67	2	1	184	136	323	3.99e-73	233	uncharacterized protein LOC111040498 [Myzus persicae]	13164	green peach aphid	Eukaryota
jg24100.t1	ref|XP_008179904.1|	59.259	189	71	2	1	184	136	323	1.21e-72	232	uncharacterized protein LOC103308396 [Acyrthosiphon pisum]<>N-acetylmuramoyl-L-alanine amidase [Acyrthosiphon pisum]	7029	pea aphid	Eukaryota
jg24100.t1	emb|VVC32798.1|	56.915	188	75	2	1	183	112	298	5.82e-67	217	Hypothetical protein CINCED_3A010942 [Cinara cedri506608	Cinara cedri	Eukaryota
jg24100.t1	emb|VVC32799.1|	56.915	188	75	2	1	183	119	305	6.71e-67	217	N-acetylmuramoyl-L-alanine amidase domain [Cinara cedri]	506608	Cinara cedri	Eukaryota
jg24100.t1	emb|VVC32797.1|	56.915	188	75	2	1	183	110	296	7.35e-67	216	Hypothetical protein CINCED_3A010942 [Cinara cedri506608	Cinara cedri	Eukaryota`

Best

YY

**Comment by peterthorpe5** [comment]
Hi YY,

Your BLAST command is not quite right: You need to following coloumns:

  #qseqid sseqid  pident  length  mismatch        gapopen qstart  qend    sstart  send    evalue  bitscore        salltitles      staxids       
  scientific_name scomnames       sskingdoms


When you ask for outformt 6 it alread yhas up to the following:

   -outfmt "6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore .

So when you ask again you get duplicate information coming out. 


You should have asked:

  -outfmt "6 salltitles staxids scientific_name scomnames sskingdoms"

You don't need to re run it, you can "cut" the columns using linux cut -f .... However, you blast output does not seem to be \t (tab) separated, which is very weird.  You may need to write a script to fix this before trying to "cut" your columns of interest. 

cheers,

Pete
