### ISSUE TITLE
fail to run Diamond_blast_to_taxid.py

### ISSUE THREAD

**Issue by jie11owen** [peterthorpe5/public_scripts#2]
Dear Peter,

I feel so lucky to find such a scirpt you wrote to solve the taxid problem from diamond output. However, when I run Diamond_blast_to_taxid.py, I got a problem like this:
**Traceback (most recent call last):
  File "Diamond_blast_to_taxid.py", line 599, in <module>
    parse_diamond_tab(diamond_tab_output, path_files, gi_taxid_prot, categories, names, gi_to_des, outfile)
  File "Diamond_blast_to_taxid.py", line 170, in parse_diamond_tab
    taxon_to_kingdom = assign_cat_to_dic(categories)
  File "Diamond_blast_to_taxid.py", line 100, in assign_cat_to_dic
    kingdom_tax_id[int(tax_id)]= kingdom_dic[kingdom]
KeyError: 'O'**

Do you know what kind of mistake I might make .
Thanks for your time and help.

**Comment by peterthorpe5** [comment]
Hi Jie11owen.

Can you please return the top info from each file used by typing: head NAME_PF_FILE.

Also, can you tell me the exact command you used to run the script. I take it you set up the database before hand?
Pete

**Comment by peterthorpe5** [comment]
Im re-running the "making database" steps myself, as I think NCBI have changed the format of one of these files. Also, it looks like your run failed when trying to get the data for an entry with tax_id = 0 ... I will look into this. As you know making the DB take a couple of hours.

**Comment by peterthorpe5** [comment]
OK. I know what is going wrong here. Can you type head on the nr.fasta file that you used to make the database with? The fasta file we have on our servers here may be a  little bit old now and it still uses gi numbers (if they have altered this). For example my blast output is:

TRINITY_DN10008_c0_g2_i1|m.50805    gi|685832877|emb|CEF67798.1|              46.9        49           26           0              22           70                110         158         1.0e-06 62.0

Whereas your file (look at column 2):
seq1370_len536_cov47 66813510 56.2 48 21 0 144 1 882 929 1.70E-08 54.7

So in the second column I get the gi number. I want to see how your nr.fasta looks please.


The James Hutton Institute is a Scottish charitable company limited by guarantee.
Registered in Scotland No. SC374831
Registered Office: The James Hutton Institute, Invergowrie Dundee DD2 5DA.
Charity No. SC041796

**Comment by jie11owen** [comment]
I got the same output format  like yours (i.e. gi|685832877|emb|CEF67798.1| ) at the begining, but when I run the script, it reported the error. So I changed the blast output using excel and then got the format like this (seq1370_len536_cov47 66813510 56.2 48 21 0 144 1 882 929 1.70E-08 54.7). Should I changed it to “seq1370_len536_cov47 gi|66813510 56.2 48 21 0 144 1 882 929 1.70E-08 54.7” ？


The head of my nr.fasta is: 
**>gi|66816243|ref|XP_642131.1| hypothetical protein DDB_G0277827 [Dictyostelium discoideum AX4] >gi|1705556|sp|P54670.1|CAF1_DICDI RecName: Full=Calfumirin-1; Short=CAF-1 >gi|793761|dbj|BAA06266.1| calfumirin-1 [Dictyostelium discoideum AX2] >gi|60470106|gb|EAL68086.1| hypothetical protein DDB_G0277827 [Dictyostelium discoideum AX4]
MASTQNIVEEVQKMLDTYDTNKDGEITKAEAVEYFKGKKAFNPERSAIYLFQVYDKDNDGKITIKELAGDIDFDKALKEY
KEKQAKSKQQEAEVEEDIEAFILRHNKDDNTDITKDELIQGFKETGAKDPEKSANFILTEMDTNKDGTITVKELRVYYQK
VQKLLNPDQ**

**Comment by peterthorpe5** [comment]
Never ever use Excel to change data with is going to go into scripts. It changes thing without you knowing!
I have found the problem. In the new catergories.dmp file from NCBI, there is a new category which was not available when I coded it called “O”.
I am fixing this now.

**Comment by jie11owen** [comment]
Thanks for your suggestions. I will not use excel any more. I am looking forward the newly revised script.

**Comment by jie11owen** [comment]
Thanks for your suggestions, I will not use excel any more. I am looking forward to your newly revised script.

**Comment by peterthorpe5** [comment]
This is now updated and should work. Please use the file with the gi numbers in the second colomn. 

Enjoy! Pete

**Comment by jie11owen** [comment]
It works now. Thank you so much for your kind help.

**Comment by peterthorpe5** [comment]
☺
